import CustomerController from "../controllers/Customer.Controller.js";
import { Router } from 'express';
const customerRouter = Router();
customerRouter.post('/new', CustomerController.createCustomer);
customerRouter.get('/all', CustomerController.getAllCustomers);
customerRouter.get('/:id', CustomerController.getCustomerById);
customerRouter.delete('/delete/:id', CustomerController.deleteCustomerById);
customerRouter.put('/update/:id', CustomerController.updateCustomerById);
customerRouter.put('/disable/:id', CustomerController.disableCustomer);
export default customerRouter;